### ISSUE TITLE
Mixed Content Issue

### ISSUE THREAD

**Issue by luthfifr** [wildantea/php-backend-generator#3]
Halo Kang Wildan, saya baru install adminlte dari repo git ini, instalasi berhasil. Tapi pas abis login tampilannya jadi kacau, screenshotnya sbg berikut: http://prntscr.com/d733if.
Mohon bantuannya kang, hatur nuhun.

update: saya sudah tahu penyebabnya.

**Comment by agustaja** [comment]
Gan @luthfifr bisa bantu, kenapa tampilannya error, dan solusi nya bagaimana ? @wildantea

**Comment by luthfifr** [comment]
@agustaja kalau tidak salah itu solusinya saya paksa load content via https, karena sudah lama sekali saya sudah tidak ingat pastinya seperti apa saya paksanya. Worst casenya sih Anda overwrite satu-satu hyperlink konten yang dari http. Maaf tidak bisa membantu banyak.
