### ISSUE TITLE
page created doubled form

### ISSUE THREAD

**Issue by luthfifr** [wildantea/php-backend-generator#5]
Kang Wildan, ini saya ada masalah lagi, saya membuat halaman untuk mengatur produk, tetapi ada masalah pada halaman edit produknya, form nya kedouble, kayak gini http://prntscr.com/d7ivzt. Untuk tambah produk sama detail produknya tidak. Padahal saya tidak ada mengedit file _edit.php nya. Bisa tolong bantu?

Terima kasih.

**Comment by wildantea** [comment]
Hapus lagi, buat lagi

**Comment by luthfifr** [comment]
not effective but it's working, thank you
