### ISSUE TITLE
Cant upload image

### ISSUE THREAD

**Issue by luthfifr** [wildantea/php-backend-generator#6]
Kang wildan, saya gak bisa upload image nih di page yang saya tambahkan sendiri tapi lewat UI Page/Menu, error message-nya kayak gini:
![screenshot at nov 18 20-57-45](https://cloud.githubusercontent.com/assets/22187764/20432468/e70a24b4-add1-11e6-9811-41a777ed24f3.png)

Karena itu file plugin, jadi menurut saya error messagenya misleading, kira-kira kenapa ya?

**Comment by wildantea** [comment]
Debug aja, console.log,

**Comment by luthfifr** [comment]
problem solved
